server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: mopl-core
  profiles:
    active: ${PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  max-active: 1
  access-token:
    secret: ${JWT_ACCESS_TOKEN_KEY:G3yksXYpKcPvNOHv5NbHuqylOuTIYEqGVY6INF2UX8OJRdyUo+rRCJmdq6Th82CGUoBOUv7WgMcxZxBiE0VIcg==}
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRCATION_MS}
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_KEY:QsMI+9J9Aunm9vWRJbwSG87ICRuasbant8f6A4jxj7Qrq3ohYWuUf5XM1Tb29DHcSW7xVeHZVrw95YFlJkD0Ag==}
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRCATION_MS}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, prometheus

  endpoint:
    health:
      show-details: always

  health:
    redis:
      enabled: false

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:your-dev-access-key}
      secret-key: ${AWS_SECRET_KEY:your-dev-secret-key}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME:mopl-images}
    stack:
      auto: false



init:
  admin:
    email: ${INIT_ADMIN_EMAIL:admin@mopl.com}
    password: ${INIT_ADMIN_PASSWORD:1234qwer}
  user:
    email: ${INIT_USER_EMAIL:test@mopl.com}
    password: ${INIT_USER_PASSWORD:1234qwer}