server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: mopl-core
  profiles:
    active: ${PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  max-active: 1
  access-token:
    secret: ${JWT_ACCESS_TOKE_KEY:G3yksXYpKcPvNOHv5NbHuqylOuTIYEqGVY6INF2UX8OJRdyUo+rRCJmdq6Th82CGUoBOUv7WgMcxZxBiE0VIcg==}
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRCATION_MS}
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_KEY:QsMI+9J9Aunm9vWRJbwSG87ICRuasbant8f6A4jxj7Qrq3ohYWuUf5XM1Tb29DHcSW7xVeHZVrw95YFlJkD0Ag==}
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRCATION_MS}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env

  endpoint:
    health:
      show-details: always

  health:
    redis:
      enabled: false

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:your-dev-access-key}
      secret-key: ${AWS_SECRET_KEY:your-dev-secret-key}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME:mopl-images}
    stack:
      auto: false



init:
  admin:
    email: ${INIT_ADMIN_EMAIL:admin@mopl.com}
    password: ${INIT_ADMIN_PASSWORD:1234qwer}
  user:
    email: ${INIT_USER_EMAIL:test@mopl.com}
    password: ${INIT_USER_PASSWORD:1234qwer}

