server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batch
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 60s

init:
  admin:
    email: "admin@test.com"
    password: 1234qwer
  user:
    email: "test@test.com"
    password: 1234qwer


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

search:
  engine: elasticsearch
