spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    driver-class-name: org.postgresql.Driver
    username: app
    password: app1234

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 60s

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE

search:
  engine: elasticsearch
