spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app
    driver-class-name: org.postgresql.Driver
    username: app
    password: app1234
    hikari:
      maximum-pool-size: 30

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: mopl-websocket-sse
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: manual
      missing-topics-fatal: false

mopl:
  kafka:
    topics:
      notifications: ${MOPL_KAFKA_TOPICS_NOTIFICATIONS:notification.events}
      watching-session-started: ${MOPL_KAFKA_TOPICS_WATCHING_SESSION_STARTED:watching.session.started}


logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    com.mopl: DEBUG