version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/spring
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/starts.sh
      timeout: 300
      runas: ubuntu
