FROM nginx:alpine

COPY ./nginx/nginx.conf.deploy /etc/nginx/nginx.conf.deploy

COPY ./nginx/static /usr/share/nginx/html/

RUN apk add --no-cache curl

EXPOSE 80 443

CMD ["/bin/sh", "-c", "envsubst '${SPRING_ALB_DNS} ${WEBSOCKET_HOST}' < /etc/nginx/nginx.conf.deploy > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
